name: test
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=eigen
  - absl-py=0.11.0=py37h06a4308_0
  - aiohttp=3.6.3=py37h7b6447c_0
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py37_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h7b6447c_0
  - ca-certificates=2020.10.14=0
  - cachetools=4.1.1=py_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.6.20=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37h06a4308_1003
  - click=7.1.2=py_0
  - cryptography=3.2.1=py37h3c74f83_1
  - dbus=1.13.6=hfdff14a_1
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.3.1=h3215721_1
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.4=h7ca028e_0
  - gast=0.3.3=py_0
  - gettext=0.19.8.1=hf34092f_1004
  - glib=2.66.2=h58526e2_0
  - gmp=6.2.0=h58526e2_4
  - gnutls=3.6.13=h79a8f9a_0
  - google-auth=1.23.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.2=pyhd3eb1b0_2
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=h58526e2_1001
  - grpcio=1.31.0=py37hf8bcb03_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h5py=2.10.0=py37hd6299e0_1
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=64.2=he1b5a44_1
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2020.2=254
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9d=h36c2ea0_0
  - keras-preprocessing=1.1.0=py_1
  - lame=3.100=h14c3975_1001
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=20_mkl
  - libcblas=3.8.0=20_mkl
  - libclang=9.0.1=default_hde54327_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglib=2.66.2=hbe7bbb4_0
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=20_mkl
  - liblapacke=3.8.0=20_mkl
  - libllvm9=9.0.1=he513fc3_1
  - libopencv=4.5.0=py37_3
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.13.0.1=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h4f3a223_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.9.2=he1b5a44_3
  - markdown=3.3.3=py37h06a4308_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - multidict=4.7.6=py37h7b6447c_1
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - nspr=4.29=he1b5a44_1
  - nss=3.59=h2c00c37_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - opencv=4.5.0=py37_3
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1h=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - pcre=8.44=he1b5a44_0
  - pillow=8.0.0=py37h9a89aac_0
  - pip=20.2.4=py37h06a4308_0
  - pixman=0.38.0=h516909a_1003
  - protobuf=3.13.0.1=py37he6710b0_1
  - pthread-stubs=0.4=h14c3975_1001
  - py-opencv=4.5.0=py37h888b3d9_3
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=pyhd3eb1b0_1
  - pysocks=1.7.1=py37_1
  - python=3.7.6=h0371630_2
  - python_abi=3.7=1_cp37m
  - qt=5.12.5=hd8c4c69_1
  - readline=7.0=h7b6447c_5
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scipy=1.5.2=py37h0b6359f_0
  - setuptools=50.3.1=py37h06a4308_1
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=2.3.0=pyh4dce500_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.3.0=eigen_py37h189e6a2_0
  - tensorflow-base=2.3.0=eigen_py37h3b305d7_0
  - tensorflow-estimator=2.3.0=pyheb71bc4_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.10=hbc83047_0
  - urllib3=1.25.11=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h7b6447c_1
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.2=py37h7b6447c_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h6597ccf_2

